FROM oven/bun:1

WORKDIR /app

COPY ./apps/http-server/package.json ./apps/http-server/package.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
RUN apt-get update -y && apt-get install -y openssl
RUN bun install

COPY ./apps/http-server ./apps/http-server

RUN bun run db:generate

EXPOSE 3001

CMD [ "bun","run","start:http" ]
