FROM oven/bun:1

WORKDIR /web
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/web/package.json ./apps/web/package.json
RUN apt-get update -y && apt-get install -y openssl
RUN bun install

COPY ./apps/web ./apps/web

RUN bun run db:generate
RUN bun run build

EXPOSE 3000

CMD [ "bun","run","start:web" ]
