name: Deploy to a Docker
on:
 push:
   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the code
       uses: actions/checkout@v2

     - name: Docker login
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build and push
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./Docker/Dockerfile.backend
         push: true
         tags: aqib2110/my-todo-backend:${{ github.sha }} 

     - name: Deploy to VM
       run: | 
         echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key 
         chmod 600 /home/runner/ssh_key
         ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@16.171.18.68 "sudo docker rm -f my-todo-backend || true && sudo docker run --name my-todo-backend -e DATABASE_URL="${{ secrets.DATABASE_URL }}" -p 3001:3001 aqib2110/my-todo-backend:${{ github.sha }}"  


